version: '3.0'

services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJECT_NAME=${APP_NAME}
        - PROJECT_VERSION=${APP_VERSION}
    image: ${APP_NAME}:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: always
    ports:
      - "8080:8080"